os: linux
language: csharp
mono: none
dotnet: 5.0.401
solution: Afi.Registration.sln
before_script:
 - export PATH=$PATH:/$HOME/.dotnet/tools
script:
 - dotnet restore
 - dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings
 - dotnet tool install -g dotnet-reportgenerator-globaltool
 - dotnet tool install -g coveralls.net
 - reportgenerator -targetdir:coveragereport -reports:**/coverage.cobertura.xml -reporttypes:"html;htmlsummary" 
 - csmacnz.Coveralls --reportgenerator -i coveragereport --repoToken $COVERALLS_REPO_TOKEN