os: windows
language: csharp
mono: none
dotnet: 5.0.401
solution: Afi.Registration.sln
script:
 - dotnet restore
 - dotnet test --collect:"XPlat Code Coverage" --settings coverlet.runsettings
 - gci -Path "*UnitTests*" -Filter coverage.opencover.xml -r | Select-Object -First 1 | % { & "$env:userprofile\.nuget\packages\coveralls.io\1.4.2\tools\coveralls.net.exe" $_.FullName -r $env:COVERALLS_REPO_TOKEN } 