os: linux
language: csharp
mono: none
dotnet: 5.0.401
solution: Afi.Registration.sln
branches:
  only: 
    - main
before_script:
  - export PATH=$PATH:/$HOME/.dotnet/tools
  - export PATH=$PATH:/$HOME/.nuget/packages/coveralls.io/1.4.2/tools
script:
  - dotnet restore
  - dotnet test --settings coverlet.runsettings
  - dotnet tool install -g dotnet-reportgenerator-globaltool
  - reportgenerator -targetdir:coveragereport -reports:**/coverage.cobertura.xml -reporttypes:"html;htmlsummary;cobertura" 
  - coveralls.net --cobertura coveragereport/Cobertura.xml -r $COVERALLS_REPO_TOKEN